### ISSUE TITLE
HttpDatastoreFactory ClassNotFoundException

### ISSUE THREAD

**Issue by Restage** [buschmais/extended-objects#166]
Since version 0.5.0 accessing a Neo4J database results in the following exception:

``` java
java.lang.ClassNotFoundException: com.buschmais.xo.neo4j.api.HttpDatastoreFactory
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1783)
    at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1633)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.buschmais.xo.neo4j.api.Neo4jXOProvider.lookupFactory(Neo4jXOProvider.java:36)
```

The error occurs when calling the execute() method of the com.buschmais.xo.api.Query class.
Currently I'm using xo.neo4j-0.6.1 to access Neo4j 2.3.1.

Is this just a configuration issue within my project or does this need to be fixed in the code?

**Comment by Restage** [comment]
OK, I see that the HttpDatastoreFactory was removed with the release of Neo4J 2.2.0.
What's the reason for this decision?

**Comment by DirkMahler** [comment]
Sorry for the late answer: The HttpDatastoreFactory was based on the Neo4j java-rest-binding (https://github.com/neo4j-contrib/java-rest-binding) which is no longer actively developed and does not work as expected with newer Neo4j releases - that's why support has been dropped.
Note: It's planned to support the new BOLT protocol as soon as Neo4j 3 is available.

**Comment by DirkMahler** [comment]
New Neo4j 3.x support via Bolt has been added in 0.8.0
